[WIP] Read autosubmit pragma and send it in the response
dimagi/formplayer pull request #786
Opened 2020-12-03 11:31 UTC by sravfeyn

https://dimagi-dev.atlassian.net/browse/USH-480

2020-12-04 04:37 UTC, ctsims approved these changes
Hi Sravan. Good to see your inputs on this, this looks good to me.

2020-12-04 09:56 UTC, sravfeyn commented on src/main/java/org/commcare/formplayer/beans/menus/BaseResponseBean.java
> +    protected boolean shouldAutoSubmit;
I am having trouble having this attributed be returned in the final JSON that the front-end gets. I did `gradle clean, deleted formplayer.jar and built formplayer again. But still, the final JSON didn't have this attribute. Is there any other serializer where I need to add this? 

FWIW just to make sure I compiled correctly, when I renamed `clearSession` var in all palces of the code and the final JSON reflected that change. So, I am not sure what else am I missing to get `shouldAutoSubmit` passed into final formplayer JSON.

Any clues? @ctsims @calellowitz

2020-12-04 22:02 UTC, ctsims requested changes

2020-12-04 22:02 UTC, ctsims commented on src/main/java/org/commcare/formplayer/beans/menus/BaseResponseBean.java
> +    public void setclearSession(boolean clearSession) {
This make break the JSON output, which I believe is defined by these getters and setters

2020-12-04 22:02 UTC, ctsims commented on src/main/java/org/commcare/formplayer/beans/menus/BaseResponseBean.java
> +    public void shouldAutoSubmit(boolean shouldAutoSubmit) {
I believe you need to add a getter (getShouldAutoSubmit) to the class or provide a method annotation for the field to be included in the JSON payload for the bean.

2020-12-23 08:46 UTC, sravfeyn commented
QA finished, @calellowitz this is good to go now?

https://dimagi-dev.atlassian.net/browse/QA-2165

2020-12-24 03:17 UTC, calellowitz commented
Yeah, good from me (and I fixed Clayton's concern). I feel weird approving since two of the commits are mine, but seems good.

2020-12-24 03:17 UTC, calellowitz approved these changes

2020-12-28 13:31 UTC, merged